Repository chef/effortless, pull requests merged in 2019-07, with the labels that each got.

#36 resolve issue with Windows gems
  scaffolding-chef-infra/lib/scaffolding.ps1
Labels: Bug

#46 add ci checks
  .expeditor/config.yml
  .expeditor/verify.scaffolding-chef-infra.yml
  bin/ci/build-and-run-tests.sh
  bin/ci/check-bad-patterns.sh
  bin/ci/check-bldr-toml.sh
  bin/ci/check-default-variables.sh
  bin/ci/check-pre-commit.sh
  bin/ci/shellcheck.sh
Labels: Enhancement

#45 [scaffolding-chef-infra] fix policyfiles-to-policyfile
  scaffolding-chef-infra/lib/scaffolding.ps1
  scaffolding-chef-infra/lib/scaffolding.sh
Labels: Bug

#48 [scaffolding-chef-infra] add examples
  .expeditor/templates/welcome.mustache
  .pre-commit-config.yaml
  bin/bootstrap.ps1
  bin/bootstrap.sh
  bin/ci/build-and-run-tests.sh
  bin/ci/check-bad-patterns.sh
  bin/ci/check-bldr-toml.sh
  bin/ci/check-default-variables.sh
  bin/ci/check-pre-commit.sh
  bin/ci/shellcheck.sh
  bin/pre-commit/bad-patterns.sh
  bin/pre-commit/bldr-toml.sh
  bin/pre-commit/default-variables.sh
  docs/examples/linux-hardening/cookbooks/hardening/files/default/auditd.conf
  docs/examples/linux-hardening/cookbooks/hardening/metadata.rb
  docs/examples/linux-hardening/cookbooks/hardening/recipes/default.rb
  docs/examples/linux-hardening/cookbooks/hardening/recipes/remediation.rb
  docs/examples/linux-hardening/cookbooks/hardening/templates/default/filesystem_blacklisting.erb
  docs/examples/linux-hardening/cookbooks/patching/attributes/default.rb
  docs/examples/linux-hardening/cookbooks/patching/metadata.rb
  docs/examples/linux-hardening/cookbooks/patching/recipes/default.rb
  docs/examples/linux-hardening/habitat/default.toml
  docs/examples/linux-hardening/habitat/plan.sh
  docs/examples/linux-hardening/policyfile/base.rb
  docs/examples/windows-hardening/cookbooks/hardening/metadata.rb
  docs/examples/windows-hardening/cookbooks/hardening/recipes/default.rb
  docs/examples/windows-hardening/habitat/default.toml
  docs/examples/windows-hardening/habitat/plan.ps1
  docs/examples/windows-hardening/policyfile/base.rb
  scaffolding-chef-infra/lib/scaffolding.sh
Labels: Documentation

#49 [scaffolding-chef-infra] fixes a bug where deps were not cascading correctly
  scaffolding-chef-infra/plan.ps1
Labels: Bug

#50 [scaffolding-chef-infra] fix policyfile path issues
  scaffolding-chef-infra/lib/scaffolding.ps1
Labels: Bug

#51 Release version 0.7.0
  VERSION
  docs/examples/linux-hardening/policyfiles/base.rb
  docs/examples/windows-hardening/habitat/plan.ps1
  docs/examples/windows-hardening/policyfiles/base.rb
  scaffolding-chef-infra/lib/scaffolding.ps1
  scaffolding-chef-infra/lib/scaffolding.sh
  scaffolding-chef-infra/plan.ps1
Labels: Documentation

#55 Fix export of policy archive on windows and fix directory creation
  scaffolding-chef-infra/lib/scaffolding.ps1
Labels: Bug

#56 fixing readme to have correct key for automate server_url on infra scaffolding
  README.md
  docs/examples/linux-hardening/habitat/default.toml
  docs/examples/windows-hardening/habitat/default.toml
Labels: Bug, Documentation

#58 [scaffolding-chef-infra] Allow users to override CACert bundle with scaffold_cacerts
  .gitignore
  README.md
  docs/examples/linux-hardening/habitat/default.toml
  docs/examples/windows-hardening/habitat/default.toml
  scaffolding-chef-infra/lib/scaffolding.sh
  scaffolding-chef-infra/plan.ps1
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/files/default/auditd.conf
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/metadata.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/recipes/default.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/recipes/remediation.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/templates/default/filesystem_blacklisting.erb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/patching/attributes/default.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/patching/metadata.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/patching/recipes/default.rb
  scaffolding-chef-infra/tests/linux-hardening/habitat/plan.sh.test
  scaffolding-chef-infra/tests/linux-hardening/policyfiles/base.rb
Labels: Enhancement

#67 [scaffolding-chef-infra] fix default varible setting
  scaffolding-chef-infra/lib/scaffolding.ps1
Labels: Bug

#66 Add scaffolding for inspec on windows
  scaffolding-chef-inspec/lib/scaffolding.ps1
  scaffolding-chef-inspec/plan.ps1
Labels: Enhancement

#71 Port the windows inspec example
  examples/windows-audit/controls/example.rb
  examples/windows-audit/habitat/plan.ps1
  examples/windows-audit/inspec.yml
Labels: Documentation

#75 [scaffolding-chef-inspec] fix left out interval
  README.md
  scaffolding-chef-inspec/lib/scaffolding.ps1
  scaffolding-chef-inspec/lib/scaffolding.sh
Labels: Bug

#79 override naive issue templates
  .github/issue_template.md
  .github/pull_request_template.md
Labels: Documentation

#74 [scaffolding-chef-inspec] Added default.toml to windows-audit example
  README.md
  examples/linux-hardening/habitat/default.toml
  examples/windows-hardening/habitat/default.toml
Labels: Documentation

#82 Add contributing.md
  CODEOWNERS
  CONTRIBUTING.md
Labels: Documentation

#83 Update linux example with heavy annotations
  .github/CODEOWNERS
  .gitignore
  README.md
  examples/infra-linux-hardening/README.md
  examples/infra-linux-hardening/cookbooks/hardening/files/default/auditd.conf
  examples/infra-linux-hardening/cookbooks/hardening/metadata.rb
  examples/infra-linux-hardening/cookbooks/hardening/recipes/default.rb
  examples/infra-linux-hardening/cookbooks/hardening/recipes/remediation.rb
  examples/infra-linux-hardening/cookbooks/hardening/templates/default/filesystem_blacklisting.erb
  examples/infra-linux-hardening/cookbooks/patching/attributes/default.rb
  examples/infra-linux-hardening/cookbooks/patching/metadata.rb
  examples/infra-linux-hardening/cookbooks/patching/recipes/default.rb
  examples/infra-linux-hardening/habitat/default.toml
  examples/infra-linux-hardening/habitat/plan.sh
  examples/infra-linux-hardening/policyfiles/base.rb
  examples/infra-linux-policyfile-cookbook/.gitignore
  examples/infra-linux-policyfile-cookbook/LICENSE
  examples/infra-linux-policyfile-cookbook/Policyfile.rb
  examples/infra-linux-policyfile-cookbook/README.md
  examples/infra-linux-policyfile-cookbook/chefignore
  examples/infra-linux-policyfile-cookbook/habitat/plan.sh
  examples/infra-linux-policyfile-cookbook/kitchen.yml
  examples/infra-linux-policyfile-cookbook/metadata.rb
  examples/infra-linux-policyfile-cookbook/recipes/default.rb
  examples/infra-linux-policyfile-cookbook/spec/spec_helper.rb
  examples/infra-linux-policyfile-cookbook/spec/unit/recipes/default_spec.rb
  examples/infra-linux-policyfile-cookbook/test/integration/default/default_test.rb
  examples/infra-linux-policyfile-cookbook/test/scripts/provisioner.sh
  examples/infra-windows-hardening/cookbooks/hardening/metadata.rb
  examples/infra-windows-hardening/cookbooks/hardening/recipes/default.rb
  examples/infra-windows-hardening/habitat/plan.ps1
  examples/infra-windows-hardening/policyfiles/base.rb
  examples/inspec-windows-audit/controls/example.rb
  examples/inspec-windows-audit/habitat/plan.ps1
  examples/inspec-windows-audit/inspec.yml
  examples/linux-hardening/habitat/plan.sh
  examples/terraform/aws-centos7/centos7.tf
  examples/terraform/aws-centos7/example.tfvars
  examples/terraform/aws-centos7/main.tf
  examples/terraform/aws-centos7/outputs.tf
  examples/terraform/aws-centos7/security.tf
  examples/terraform/aws-centos7/variables.tf
  examples/terraform/aws-windows2016/example.tfvars
  examples/terraform/aws-windows2016/main.tf
  examples/terraform/aws-windows2016/outputs.tf
  examples/terraform/aws-windows2016/security.tf
  examples/terraform/aws-windows2016/variables.tf
  examples/terraform/aws-windows2016/windows2016.tf
  examples/terraform/templates/hab-sup.service
  examples/terraform/templates/install-hab.sh.tpl
Labels: Documentation

#84 Fix issue with building a profile with Automate dependency
  scaffolding-chef-inspec/lib/scaffolding.ps1
  scaffolding-chef-inspec/tests/windows/inspec-a2-profile-dep/controls/example.rb
  scaffolding-chef-inspec/tests/windows/inspec-a2-profile-dep/habitat/plan.ps1
  scaffolding-chef-inspec/tests/windows/inspec-a2-profile-dep/inspec.yml
  scaffolding-chef-inspec/tests/windows/inspec-git-profile-dep/controls/example.rb
  scaffolding-chef-inspec/tests/windows/inspec-git-profile-dep/habitat/plan.ps1
  scaffolding-chef-inspec/tests/windows/inspec-git-profile-dep/inspec.yml
Labels: Enhancement

#92 tell a better story for new and existing users
  README.md
  examples/infra-linux-hardening/policyfiles/base.rb
  examples/infra-windows-hardening/README.md
  examples/infra-windows-hardening/habitat/plan.ps1
Labels: Documentation

#100 Add real automated ci tests
  .expeditor/verify.scaffolding-chef-infra.yml
  .pre-commit-config.yaml
  bin/ci/build-and-run-tests.sh
  bin/ci/check-bldr-toml.sh
  bin/pre-commit/bldr-toml.sh
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/files/default/auditd.conf
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/metadata.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/recipes/default.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/recipes/remediation.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/hardening/templates/default/filesystem_blacklisting.erb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/patching/attributes/default.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/patching/metadata.rb
  scaffolding-chef-infra/tests/linux-hardening/cookbooks/patching/recipes/default.rb
  scaffolding-chef-infra/tests/linux-hardening/habitat/default.toml
  scaffolding-chef-infra/tests/linux-hardening/habitat/plan.sh.test
  scaffolding-chef-infra/tests/linux-hardening/policyfiles/base.rb
  scaffolding-chef-infra/tests/test.bats
  scaffolding-chef-infra/tests/test.sh
  scaffolding-chef-infra/tests/user-linux/cookbooks/ci/metadata.rb
  scaffolding-chef-infra/tests/user-linux/cookbooks/ci/recipes/default.rb
  scaffolding-chef-infra/tests/user-linux/habitat/plan.sh
  scaffolding-chef-infra/tests/user-linux/policyfiles/ci.rb
  scaffolding-chef-infra/tests/user-windows/cookbooks/hardening/metadata.rb
  scaffolding-chef-infra/tests/user-windows/cookbooks/hardening/recipes/default.rb
  scaffolding-chef-infra/tests/user-windows/habitat/plan.ps1
  scaffolding-chef-infra/tests/user-windows/policyfiles/ci.rb
  scaffolding-chef-infra/tests/windows-hardening/cookbooks/hardening/metadata.rb
  scaffolding-chef-infra/tests/windows-hardening/cookbooks/hardening/recipes/default.rb
  scaffolding-chef-infra/tests/windows-hardening/habitat/default.toml
  scaffolding-chef-infra/tests/windows-hardening/habitat/plan.ps1.test
  scaffolding-chef-infra/tests/windows-hardening/policyfiles/base.rb
Labels: Testing

#110 [scaffolding-chef-infra] add tests and test package for custom cacert override
  bin/ci/build-and-run-tests.sh
  examples/terraform/aws-windows2016/security.tf
  examples/terraform/aws-windows2016/windows2016.tf
  scaffolding-chef-infra/tests/cacerts/cert-add.pem
  scaffolding-chef-infra/tests/cacerts/habitat/plan.sh
  scaffolding-chef-infra/tests/test.bats
  scaffolding-chef-infra/tests/test.sh
  scaffolding-chef-infra/tests/user-linux/habitat/plan.sh
Labels: Testing

#114 [scaffolding-chef-infra] Add license acceptance flow for Chef Infra
  examples/infra-linux-hardening/habitat/default.toml
  examples/infra-linux-policyfile-cookbook/habitat/default.toml
  examples/infra-windows-hardening/habitat/default.toml
  scaffolding-chef-infra/lib/scaffolding.ps1
  scaffolding-chef-infra/lib/scaffolding.sh
  scaffolding-chef-infra/tests/user-linux/habitat/default.toml
  scaffolding-chef-infra/tests/user-windows/cookbooks/ci/metadata.rb
  scaffolding-chef-infra/tests/user-windows/cookbooks/ci/recipes/default.rb
  scaffolding-chef-infra/tests/user-windows/habitat/default.toml
  scaffolding-chef-infra/tests/user-windows/habitat/plan.ps1
  scaffolding-chef-infra/tests/user-windows/policyfiles/ci.rb
Labels: Enhancement
